### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by patoigz** [elfalem/Leaflet.curve#1]
Is there a way? To use this "lib" but with Leaflet 0.7.5?

**Comment by elfalem** [comment]
Unfortunately, this plugin is not compatible with Leaflet 0.7.5 because significant changes have been made to the Leaflet library after version 0.7.5.

**Comment by patoigz** [comment]
Ok... If i work in something. I will share it.
Because if i create a curve using Polylines & Bezier is extremely costly. And i need render about 180K curves!

**Comment by elfalem** [comment]
I recommend upgrading to version 1.0 or later of Leaflet which has a lot of improvements.
