### ISSUE TITLE
midpoint automatically

### ISSUE THREAD

**Issue by spmsupun** [elfalem/Leaflet.curve#10]
when going to one curve line using M and Q we have to put midpoint statically.
EX:
```
L.curve(
            [
                'M', latlng1,
                'Q', latlng1,
                [14.33,23.66]//we don't know  this
            ], dash_straight).addTo(this.map);

```
so need a way to create that midpoint automatically from the plugin. 
using your plugin I created sample project to do that https://github.com/lifeeka/leaflet.bezier/tree/supun-dev

**Comment by elfalem** [comment]
Interesting project. Thanks.
