### ISSUE TITLE
Add text to curve

### ISSUE THREAD

**Issue by yadavdilip1729** [elfalem/Leaflet.curve#11]
I have draw a curve in leaflet map between two points. How to add text in middle of  curve line.  

my code is like that :
var curvedPath = L.curve(
					[
						'M', latlng1,
						'Q', midpointLatLng,
						latlng2
					], pathOptions).addTo(map);

**Comment by elfalem** [comment]
Unfortunately there is no feature built into this plugin to allow adding text on the curve. 

Depending on the nature of your map, perhaps you can look into adding a `<textPath>` element (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath).
