### ISSUE TITLE
set timer for the curve

### ISSUE THREAD

**Issue by kunaldhariwal** [elfalem/Leaflet.curve#12]
how the timer has to be set for the curve?
curve should disappear along with the markers.

**Comment by elfalem** [comment]
Perhaps you can use `setTimeout()` to remove the curve and markers after some time.

**Comment by kunaldhariwal** [comment]
var path = L.curve(['M',latlng2,'Q',midpointLatLng,latlng1], {snakeArray: 5, color:'grey' ,animate: {duration: 2500, iterations: 2}}).addTo(map);
                   window.setTimeout(5000,path);

This isn't working.

**Comment by kunaldhariwal** [comment]
```
 setTimeout(function () {
                var path = L.curve(['M',latlng2,'Q',midpointLatLng,latlng1], {snakeArray: 5, color:'grey' ,animate: {duration: 2500, iterations: 2}}).addTo(map);
  },5000)

```
This makes the curve to appear after 5 secs  but i want it to disappear after 5 secs

**Comment by kunaldhariwal** [comment]
Also, it gives the following error and the curve turns into a straight line.

Expression statement is not assignment or call 
 Mutable variable is accessible from closure

**Comment by elfalem** [comment]
You want to set the timer on the removal not addition of the curve.

```
//add the curve 
var path = L.curve(['M',latlng2,'Q',midpointLatLng,latlng1], {snakeArray: 5, color:'grey' ,animate: {duration: 2500, iterations: 2}}).addTo(map);

setTimeout(function() { 
     //if you have other curves/markers, you can remove them here as well
     path.remove();
}, 5000)

```

**Comment by kunaldhariwal** [comment]
Thank you so much. It worked!
