### ISSUE TITLE
Support canvas renderer

### ISSUE THREAD

**Issue by chazsolo** [elfalem/Leaflet.curve#15]
Is there any plan to provide support for the Canvas renderer in the future? Due to performance issues using SVG and animations (with the amount of data we have to render at once) I'd love to switch over to using the canvas renderer but we lose all of our arcs, and I've yet to find a good replacement.

**Comment by elfalem** [comment]
I've just added basic support for Canvas rendering. However, animations do not work since the Web Animations API doesn't work with Canvas. I'm not sure how to bridge this discrepancy between the two renderers but I'm open to suggestions.

Another caveat, checks on whether a point resides within a shape or not actually use the shapes rectangular bounding box. I haven't tested it but if click event listeners are attached to shapes, I think they will be triggered by clicking close to, but not on, the shape.

Any feedback on this implementation is welcome.

**Comment by chazsolo** [comment]
I don't have extensive experience using canvas, but I'd be glad to look and see if I can help in any way. Thankfully the first iteration of our maps doesn't require any animation or interaction with the arc, it's just a visual indicator of a relationship, so I'd be happy with whatever works!

**Comment by elfalem** [comment]
OK. I've pushed version 0.3.0 to npm which allows Canvas rendering.

**Comment by chazsolo** [comment]
This update works great; really appreciate you responding so quickly! There is one minor problem I'm having, and that's with re-renders (using React). Everything looks fine until we change some options and re-render the component. The arcs are being redrawn but never cleared, so old arcs remain. I've tried clearing the canvas on a render with `context.clearRect(0, 0, canvas.width, canvas.height)` but for some reason that isn't working. I _can_ clear the canvas from console, grabbing the context of the DOM, so in essence our clear function should work:

```
// we call cleanArcs any time the data is changing
cleanArcs = () => {
  if (this.leafletMap) {
    const pane = this.leafletMap.getPane(PANES.Arcs)
    const canvas = pane.querySelector('canvas')
    
    if (canvas) {
      // context here is defined and is the correct one
      const context = canvas.getContext('2d')
      
      context.clearRect(0, 0, canvas.width, canvas.height)
    }
  }
}
```

Passing in opacity for the stroke:

```
L.curve(['M', latLng, 'Q', midPointLatLng, originLatLng], {
  color: strokeColor,
  opacity: ghost ? 0.2 : 1,
  pane: PANES.Arcs,
  stroke: true,
  weight: 1.4,
}).addTo(this.leafletMap)
```

Is there something I'm missing or is this more of a problem with React and re-rendering?

**Comment by chazsolo** [comment]
@elfalem After poking at it for a while I realized that was the wrong way to go about it, and instead need to clear out the layers from the map instead

```javascript
cleanArcs = () => {
  this.arcs.forEach(arc => this.leafletMap.removeLayer(arc))
}
```

and it works beautifully. Thanks again for the update!

**Comment by elfalem** [comment]
Great! Glad to hear it's working.
