### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by kindrebo** [elfalem/Leaflet.curve#17]
Nice plugin.

I hope I am wrong, but shapes do not seem to be drawn in IE and Edge.

**Comment by elfalem** [comment]
It looks like this is due to lack of support for Element.animate in IE and Edge (https://caniuse.com/#feat=web-animation). Are you looking to animate the shapes or just draw non animated ones?

**Comment by kindrebo** [comment]
Indeed, non-animated ones seem to be drawn in IE when the animated shapes are not included. Thank you for pointing in the right direction, as well as for the compatibility-link.
