### ISSUE TITLE
Animated curve becomes dashed when zoomed

### ISSUE THREAD

**Issue by n3d1117** [elfalem/Leaflet.curve#19]
Hello!
When animating a curve, it becomes dashed once I start to zoom in. 
If I remove the animation, it works fine. I've tested it straight from the demo site. Am I missing something? Thanks

![leaflet_curve](https://user-images.githubusercontent.com/11541888/53292871-eca98e80-37c9-11e9-9a3c-5f5d1f17ec58.gif)

**Comment by elfalem** [comment]
Hello,

I see this issue as well. It's probably related to the recent animation changes. I will take a look when I get a chance. Thanks for reporting.

**Comment by elfalem** [comment]
Just to give an update, I have a fix for SVG already but still working on one for Canvas.

**Comment by elfalem** [comment]
A fix has been pushed for both SVG and Canvas. [v0.4.1](https://github.com/elfalem/Leaflet.curve/releases/tag/v0.4.1) has been released and published to npm.
