### ISSUE TITLE
Leaflet.curve is not compatible with leaflet.browser.print

### ISSUE THREAD

**Issue by khetamHamad** [elfalem/Leaflet.curve#24]
Hello,

I added a leaflet.browser.print button to print the map with the flows but it always returns a map without flows curves any advice or recommendations to show the curves in the maps.

Best regards.

**Comment by elfalem** [comment]
The curve layer needs to be registered with the browser print plugin. (more info: https://github.com/Igor-Vladyka/leaflet.browser.print#new-print-layersrenderers-registration)

You can use the following code to register the layer:
````
L.Control.BrowserPrint.Utils.registerLayer(
	L.Curve,
	"L.Curve",
	function(layer, utils) {
		return L.curve(layer._coords, utils.cloneOptions(layer.options));
	}
);
````

**Comment by khetamHamad** [comment]
@elfalem thank you after I added the registration code it works.
Is there any solution for the animation, when I print the map it doesn't show the full flow just a part of it because of animation.

Thanks again.

**Comment by elfalem** [comment]
You can disable animations when printing by removing the `animate` property when cloning the options.
````
L.Control.BrowserPrint.Utils.registerLayer(
	L.Curve,
	"L.Curve",
	function(layer, utils) {
		var options = utils.cloneOptions(layer.options);
		options.animate = undefined;
		return L.curve(layer._coords, options);
	}
);
````

**Comment by khetamHamad** [comment]
Thanks 👍
