### ISSUE TITLE
ReferenceError: coord is not defined

### ISSUE THREAD

**Issue by LucasMendoncaWF** [elfalem/Leaflet.curve#29]
im getting this error: ERROR ReferenceError: coord is not defined

when i try to do this: L.curve(['S', [place.lat ,place.lon],[-23.5437811, -46.6470027]], {color:'green',fill:true}).addTo(this.map);

how can i do this work?

(i'm using angular)

**Comment by elfalem** [comment]
Based on PR #30, it looks like you're using a very old version of the code.
