### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by maximusnikulin** [elfalem/Leaflet.curve#3]
Is threre some way to animate it?

**Comment by elfalem** [comment]
What type of animation? Can you provide more details?

**Comment by maximusnikulin** [comment]
I want to draw path form start to end with different delay

**Comment by elfalem** [comment]
I've added an initial implementation of an option to animate. The demo includes examples.

**Comment by maximusnikulin** [comment]
@elfalem It's so great!Thanks a lot
