### ISSUE TITLE
Leaflet Curve does not seem to want to cross the Pacific Ocean

### ISSUE THREAD

**Issue by Weilin37** [elfalem/Leaflet.curve#37]
I have an example of a curve drawn between Australia and California. The expected curve would have crossed the pacific ocean for the shortest path. Instead, it seems to cross Africa and the Atlantic Ocean.

I'd like to understand better why that is and if there is a solution to this. Thanks for your time.

**Comment by elfalem** [comment]
@Weilin37 This applies to Leaflet.js in general and is not something that's specific to Leaflet.curve. I don't have experience with this aspect but there are several Github issues discussing the crossing of the International Date Line. Please see: 
* https://github.com/rstudio/leaflet/issues/553
* https://github.com/Leaflet/Leaflet/issues/82#issuecomment-1260488

**Comment by Weilin37** [comment]
Thanks and you're right those solutions helped. Thanks
