### ISSUE TITLE
Type Support For L.Curve?

### ISSUE THREAD

**Issue by ardeora** [elfalem/Leaflet.curve#38]
Hello there! I hope you are had an amazing weekend. I have been using your leaflet plugin since a while and am absolutely grateful for it. I was wondering if you would be interested in adding type support for this plugin? I am willing to create a TypeScript declaration file for this extension 😃  Hope you have a wonderful week!

**Comment by elfalem** [comment]
Hello @ardeora! I'm glad you found the Leaflet.curve plugin to be useful. It would be a welcome addition to have type support. I  would appreciate a PR for the TypeScript declaration file.

**Comment by ardeora** [comment]
Okay awesome! I'll open a pull request soon 🥳

**Comment by ardeora** [comment]
#39 I have made a pull request. Please let me know if you would like some changes to be made. I would be happy to update them!

**Comment by elfalem** [comment]
Thank you @ardeora! The pull request looks good to me. I will merge and make a new release when I get a chance.

**Comment by ardeora** [comment]
Awesome! Thanks. Let me know if you need help with anything else :D

**Comment by elfalem** [comment]
version 0.8.0 has been published. Thanks again for your contribution!
