### ISSUE TITLE
Convert SVG path to coordinates  Curve 

### ISSUE THREAD

**Issue by ahthyun** [elfalem/Leaflet.curve#45]
Hi Team
I am having a SVG file with available path, how I can convert it to coordinates to use in Curve 
![image](https://user-images.githubusercontent.com/78398596/143556980-f679571f-525a-4d7d-bdab-068238eaf66f.png)

**Comment by elfalem** [comment]
Unfortunately that's beyond the scope of this project. I don't have GIS experience but I think you would need to georeference the SVG path. Perhaps [this tool](https://github.com/Phrogz/svg2geojson) or [this one](https://github.com/mapbox/svg-to-geojson) could be useful. A GIS specific forum such as [GIS Stack Exchange](https://gis.stackexchange.com/) might be more relevant.
