### ISSUE TITLE
Changing line weight via setStyle() blows out

### ISSUE THREAD

**Issue by vpithart** [elfalem/Leaflet.curve#46]
With leaflet v1.7.1 and Leaflet.curve 1.0.0, calling setStyle to change line weight blows out.
Reproducible in [this codepen](https://codepen.io/vpithart/pen/rNGxPrz).

```
 Uncaught TypeError: this._updateBounds is not a function
    setStyle Path.js:109
```

[This](https://github.com/Leaflet/Leaflet/blob/e3719a317ab325ed091fbbc6bfd34640fe19e13e/src/layer/vector/Path.js#L109) is where the error occurs.

**Comment by vpithart** [comment]
I'm sorry, wrong repository. This bug belongs to the forked https://github.com/onikiienko/Leaflet.curve.
(that one is a default you get via `npm install leaflet-curve`).

**Comment by elfalem** [comment]
Yeah that's an old fork which I don't think is maintained. I recommend using the package `@elfalem/leaflet-curve` instead.
