### ISSUE TITLE
ahhh,I want to know how to use command 'A'

### ISSUE THREAD

**Issue by suyanhanx** [elfalem/Leaflet.curve#5]
please tell me ,or make an example

**Comment by elfalem** [comment]
I don't plan on supporting command 'A' going forward. It's possible to approximate elliptical arcs with bezier curves. However, if you really want to use command 'A', you'll need to check out the `elliptical-arc` branch of the repository. The example.html file in there shows you how to use it.

**Comment by suyanhanx** [comment]
Oh,thank you.I just want to draw quad.Maybe you are right,I found that using bezier curve to approximate quad will get a good result while angle less than 90 degree.And I'll check the example.html.Thank you very much.This plug-in gives me a lot of help.

**Comment by suyanhanx** [comment]
That you said this plug-in was just like SVG.Yesterday I checked SVG documents of path and I used command 'A' according  to the document.But I failed.The 'A' did no effect.

**Comment by suyanhanx** [comment]
So the js file in two branches is different？

**Comment by suyanhanx** [comment]
Yep,they are different.I'll choose the one in elliptical-arc branch.Now animation does nothing to me.Command 'A' is better.Thank you again.

**Comment by elfalem** [comment]
Yes, command 'A' will only work on that branch. The animation option is new and is not available on that branch.

**Comment by suyanhanx** [comment]
Can this use relative coordinate？Using 'A'in absolute coordinate becomes troublesome in different lats.

**Comment by elfalem** [comment]
As of now there is no support for relative coordinates.
