### ISSUE TITLE
Draw marker on curve

### ISSUE THREAD

**Issue by verdie-g** [elfalem/Leaflet.curve#9]
Hi ! Is it, or will it be possible to draw marker on the curve ?

**Comment by elfalem** [comment]
Hi! Unfortunately there is no functionality in this plugin to draw markers on the curve.

There is a plugin [leaflet-distance-markers](https://github.com/adoroszlai/leaflet-distance-markers) that does this for polylines. Perhaps it could be altered to work with curves.

**Comment by verdie-g** [comment]
Thanks for you answer

**Comment by verdie-g** [comment]
Is it possible to get curve equation though ?

**Comment by elfalem** [comment]
I'm not sure exactly what you're asking for but the [standard bezier equations](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Specific_cases) may be what you're looking for.

**Comment by verdie-g** [comment]
Nevermind.
